version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - /usr/local/nexus/nexus-data:/nexus-data
    environment:
      TZ: 'Asia/Shanghai'
    mem_limit: 2g
    privileged: true